Visualização de Dados adicionada
Felipalds/combinatorial-optimization pull request #7
Opened 2022-11-10 18:15 UTC by Pfzoz

program.py fica mais clean com só o necessário pra utilizar as classes e o algoritmo, todas gerações são salvas e visualizáveis com pyplot.

2022-11-10 20:20 UTC, Felipalds requested changes

2022-11-10 20:20 UTC, Felipalds commented on genetic-algorithms/genalg.py
> +from individual import Individual
Nomes de arquivos de classe, sempre com letra maiúscula

2022-11-10 20:20 UTC, Felipalds commented on genetic-algorithms/program.py
> +            plt.show()
Dá pra trocar essas funções todas de plt por uma função show(),  para ficar mais clean

2022-11-12 00:33 UTC, Pfzoz commented on genetic-algorithms/genalg.py
> +from individual import Individual
Resolvido, nomes de outros arquivos também alterados para encaixar no padrão,

2022-11-12 00:34 UTC, Pfzoz commented on genetic-algorithms/program.py
> +            plt.show()
Resolvido, uma função só GenAlgorith.visualize realiza a função.

2022-11-12 00:36 UTC, Pfzoz commented
Novas alterações realizadas, adicionando GenAlgorithm.animate para criação da animação das gerações após a finalização do algoritmo e a opção de inserir o alpha do algoritmo.

2022-11-15 20:17 UTC, merged